# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: myapp_development
  host: db
  port: 5432
  username: postgres
  password: password

test:
  <<: *default
  database: myapp_test
  host: db
  port: 5432
  username: postgres
  password: password

production:
  <<: *default
  # Render では DATABASE_URL を使う
  url: <%= ENV["DATABASE_URL"] %>
