# fly.toml app configuration file generated for my-mysql-polished-dawn-8618 on 2025-10-16T20:51:43+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-mysql-polished-dawn-8618'
primary_region = 'nrt'

[build]
  image = 'mysql:8.0'

[http_service]
  internal_port = 3306
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
